name: Node CI

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: restore
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Type-Check
        run: yarn type-check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
